apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mini-llm

resources:
  - frontend-deployment.yaml
  - frontend-service.yaml
  - backend-external-secret.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - model-cache-pvc.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: mini-llm
      app.kubernetes.io/version: "1.0.0"
