apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mini-llm-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - mini-llm.navillasa.dev
    secretName: mini-llm-tls
