apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: ingress-patch.yaml

labels:
  - pairs:
      environment: dev
      cluster: microk8s

images:
  - name: mini-llm-backend
    newName: ghcr.io/navillasa/mini-llm-backend
    newTag: v1.0.0
  - name: mini-llm-frontend
    newName: ghcr.io/navillasa/mini-llm-frontend
    newTag: v1.0.0
