apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mini-llm-dev

resources:
- namespace.yaml
- ../../base

patches:
- path: ingress-patch.yaml

labels:
- pairs:
    cluster: microk8s
    environment: dev

images:
- name: mini-llm-backend
  newName: ghcr.io/navillasa/mini-llm-backend
  newTag: ce63c9a
- name: mini-llm-frontend
  newName: ghcr.io/navillasa/mini-llm-frontend
  newTag: ce63c9a
